# Generated by Django 3.2.2 on 2021-07-07 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Session', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RecordDate', models.DateTimeField()),
                ('ScorePoints', models.ImageField(upload_to='')),
                ('Session_Status', models.CharField(max_length=50)),
                ('Session_Score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_score', to='Session.session')),
            ],
        ),
    ]
