# Generated by Django 3.2.2 on 2021-07-11 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Accounts', '0001_initial'),
        ('Physiotherapist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='patient_user', serialize=False, to='Accounts.newuser')),
                ('Physio_Patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='Physiotherapist.physiotherapist')),
            ],
        ),
    ]
