# Generated by Django 3.2.2 on 2021-07-06 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExeercisePlan', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise_plan',
            old_name='Duration',
            new_name='Angle',
        ),
        migrations.RemoveField(
            model_name='exercise_plan',
            name='MembersToUse',
        ),
        migrations.RemoveField(
            model_name='exercise_plan',
            name='RestTime',
        ),
        migrations.AlterField(
            model_name='exercise_plan',
            name='Difficulty',
            field=models.CharField(max_length=50),
        ),
    ]
