# Generated by Django 3.2.2 on 2021-05-13 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Physiotherapist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=80, unique=True)),
                ('Description', models.CharField(max_length=250)),
                ('Game_Owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Game_Owner', to='Physiotherapist.physiotherapist')),
            ],
        ),
    ]
