# Generated by Django 3.2.2 on 2021-05-13 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='Game_Owner',
            new_name='owner',
        ),
    ]
