# Generated by Django 3.2.2 on 2021-07-11 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Patient', '0001_initial'),
        ('Physiotherapist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Patient_Favorite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Patient_Fav', to='Patient.patient')),
                ('Physio_Favorite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Physio_Fav', to='Physiotherapist.physiotherapist')),
            ],
        ),
    ]
